# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Fast CI
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: fast test

    steps:
      - uses: actions/checkout@v3

      - name: setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
          # only first java setup need enable cache
          cache: maven
      - name: setup Java 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin

      - name: build and test with Java 19
        run: ./mvnw -V --no-transfer-progress clean package
      - name: test with Java 8
        run: ./mvnw -V --no-transfer-progress surefire:test
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}
